create or replace table RAW_INSURANCE_DATA(raw_col VARIANT);

create or replace table STRUCT_INSURANCE_DATA(
  AGE INT
, SEX VARCHAR
, BMI NUMBER(5,2)
, CHILDREN INT
, SMOKER VARCHAR
, REGION VARCHAR
, CHARGES NUMBER(7,2));

create or replace table SMOKER_INSURANCE_STAT(
  REGION VARCHAR
, MIN_CHARGES NUMBER(7,2)
, MAX_CHARGES NUMBER(7,2)
);

create or replace table OBESITY_INSURANCE_STAT(
  REGION VARCHAR
, MIN_CHARGES NUMBER(7,2)
, MAX_CHARGES NUMBER(7,2)
);

create or replace table AGE_INSURANCE_STAT(
  REGION VARCHAR
, MIN_CHARGES NUMBER(7,2)
, MAX_CHARGES NUMBER(7,2)
);